"""
Fixer Module - Execute LLM-generated Fixes

Executes any kubectl command or YAML patch generated by the LLM analyzer.
Handles:
- Direct kubectl commands
- YAML file modifications
- Deployment updates
- Pod deletions and recreate
"""

import subprocess
import re
import yaml
import json
from typing import Dict, Any, Optional, List
from datetime import datetime

from config import NAMESPACE, YAML_FILE_PATH, POD_NAME


def run_cmd(cmd: str, timeout: int = 60) -> Dict[str, Any]:
    """
    Run shell command and return result.

    Returns:
        Dict with success, output, error
    """
    try:
        result = subprocess.run(
            cmd, shell=True, capture_output=True, text=True, timeout=timeout
        )
        return {
            "success": result.returncode == 0,
            "output": result.stdout,
            "error": result.stderr,
            "returncode": result.returncode
        }
    except subprocess.TimeoutExpired:
        return {
            "success": False,
            "output": "",
            "error": "Command timed out",
            "returncode": -1
        }
    except Exception as e:
        return {
            "success": False,
            "output": "",
            "error": str(e),
            "returncode": -1
        }


def parse_fix_command(command: str) -> str:
    """Clean and validate kubectl command."""
    command = command.strip()

    # Remove markdown code blocks
    command = re.sub(r'^```kubectl', '', command)
    command = re.sub(r'^```', '', command)
    command = re.sub(r'```$', '', command)

    return command.strip()


def execute_fix_command(command: str) -> Dict[str, Any]:
    """
    Execute a kubectl fix command.

    Args:
        command: The kubectl command to execute

    Returns:
        Dict with success, output, command
    """
    if not command or not command.strip():
        return {
            "success": False,
            "command": "",
            "output": "",
            "error": "Empty command"
        }

    # Parse and validate
    clean_cmd = parse_fix_command(command)

    if not clean_cmd.startswith("kubectl"):
        return {
            "success": False,
            "command": clean_cmd,
            "output": "",
            "error": "Command must start with kubectl"
        }

    print(f"\n>>> Executing: {clean_cmd}")

    # Execute
    result = run_cmd(clean_cmd, timeout=120)

    return {
        "success": result["success"],
        "command": clean_cmd,
        "output": result["output"],
        "error": result["error"],
        "returncode": result["returncode"]
    }


def apply_yaml_fix(yaml_content: str) -> Dict[str, Any]:
    """
    Apply YAML content as a fix.

    Args:
        yaml_content: YAML string to apply

    Returns:
        Dict with success and output
    """
    # Save to temp file
    import tempfile
    import os

    with tempfile.NamedTemporaryFile(mode='w', suffix='.yaml',
                                     delete=False) as f:
        f.write(yaml_content)
        temp_file = f.name

    try:
        # Apply the YAML
        result = run_cmd(f"kubectl apply -f {temp_file} -n {NAMESPACE}")

        return {
            "success": result["success"],
            "output": result["output"],
            "error": result["error"]
        }
    finally:
        # Cleanup
        try:
            os.unlink(temp_file)
        except:
            pass


def delete_and_recreate(pod_name: str = None) -> Dict[str, Any]:
    """
    Delete problematic pod and let deployment recreate it.

    Args:
        pod_name: Pod to delete

    Returns:
        Dict with success and output
    """
    pod = pod_name or POD_NAME

    if not pod:
        return {
            "success": False,
            "output": "",
            "error": "No pod name specified"
        }

    # Delete pod
    cmd = f"kubectl delete pod {pod} -n {NAMESPACE} --grace-period=0 --force"
    print(f"\n>>> Deleting pod: {pod}")

    result = run_cmd(cmd)

    return {
        "success": result["success"],
        "output": result["output"],
        "error": result["error"]
    }


def update_deployment_image(deployment: str, container: str,
                           new_image: str) -> Dict[str, Any]:
    """
    Update deployment container image.

    Args:
        deployment: Deployment name
        container: Container name
        new_image: New image (e.g., nginx:latest)

    Returns:
        Dict with success and output
    """
    cmd = f"kubectl set image deployment/{deployment} {container}={new_image}"
    print(f"\n>>> Updating image: {deployment}/{container}={new_image}")

    result = run_cmd(cmd)

    return {
        "success": result["success"],
        "output": result["output"],
        "error": result["error"]
    }


def patch_deployment(deployment: str, patch: str) -> Dict[str, Any]:
    """
    Patch deployment with JSON patch.

    Args:
        deployment: Deployment name
        patch: JSON patch string

    Returns:
        Dict with success and output
    """
    cmd = f"kubectl patch deployment {deployment} -n {NAMESPACE} -p '{patch}'"
    print(f"\n>>> Patching deployment: {deployment}")

    result = run_cmd(cmd)

    return {
        "success": result["success"],
        "output": result["output"],
        "error": result["error"]
    }


def scale_deployment(deployment: str, replicas: int) -> Dict[str, Any]:
    """
    Scale deployment.

    Args:
        deployment: Deployment name
        replicas: Number of replicas

    Returns:
        Dict with success and output
    """
    cmd = f"kubectl scale deployment {deployment} -n {NAMESPACE} --replicas={replicas}"
    print(f"\n>>> Scaling deployment: {deployment} to {replicas}")

    result = run_cmd(cmd)

    return {
        "success": result["success"],
        "output": result["output"],
        "error": result["error"]
    }


def apply_fix_from_diagnosis(diagnosis_result) -> Dict[str, Any]:
    """
    Apply a fix based on diagnosis result.

    Args:
        diagnosis_result: DiagnosisResult from analyzer

    Returns:
        Dict with success, output, fix applied
    """
    fix_applied = False
    output = ""
    error = ""

    # Try the fix command first
    if diagnosis_result.fix_command:
        result = execute_fix_command(diagnosis_result.fix_command)
        if result["success"]:
            return {
                "success": True,
                "command": diagnosis_result.fix_command,
                "output": result["output"],
                "error": "",
                "fix_type": "command"
            }
        else:
            output = result.get("output", "")
            error = result.get("error", "")

    # Try YAML if command failed
    if diagnosis_result.fix_yaml:
        result = apply_yaml_fix(diagnosis_result.fix_yaml)
        if result["success"]:
            return {
                "success": True,
                "command": "",
                "output": result["output"],
                "error": "",
                "fix_type": "yaml"
            }

    # Last resort: delete and recreate
    if POD_NAME:
        result = delete_and_recreate(POD_NAME)
        return {
            "success": result["success"],
            "command": f"kubectl delete pod {POD_NAME}",
            "output": result["output"],
            "error": result["error"],
            "fix_type": "delete_recreate"
        }

    return {
        "success": False,
        "command": diagnosis_result.fix_command or "",
        "output": output,
        "error": error or "No fix available",
        "fix_type": "none"
    }


def retry_with_backoff(attempt: int, max_retries: int = 5) -> int:
    """
    Calculate backoff delay for retry.

    Args:
        attempt: Current attempt number (0-indexed)
        max_retries: Maximum retries

    Returns:
        Seconds to wait
    """
    import random

    if attempt >= max_retries - 1:
        return 0

    # Exponential backoff with jitter
    delay = min(2 ** attempt * 2, 60)  # Max 60 seconds
    jitter = random.uniform(0, 5)

    return int(delay + jitter)


if __name__ == "__main__":
    # Test fix execution
    test_cmd = "kubectl get pods -n default"
    result = execute_fix_command(test_cmd)
    print(f"Success: {result['success']}")
    print(f"Output: {result['output'][:200]}")